[W 2024-01-25 11:16:01,467] Trial 0 failed with parameters: {'min_samples_leaf': 5, 'max_depth': 16, 'min_samples_split': 8} because of the following error: ValueError('If using all scalar values, you must pass an index').
Traceback (most recent call last):
  File "/home/wang-jian-an/venv-python310/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/wang-jian-an/venv-python310/lib/python3.10/site-packages/optuna/integration/wandb.py", line 225, in wrapper
    return func(trial)
  File "/tmp/ipykernel_2980907/1041603510.py", line 58, in objective
    parallel_coordinates_plot = px.parallel_coordinates(
  File "/home/wang-jian-an/venv-python310/lib/python3.10/site-packages/plotly/express/_chart_types.py", line 1418, in parallel_coordinates
    return make_figure(args=locals(), constructor=go.Parcoords)
  File "/home/wang-jian-an/venv-python310/lib/python3.10/site-packages/plotly/express/_core.py", line 2076, in make_figure
    args = build_dataframe(args, constructor)
  File "/home/wang-jian-an/venv-python310/lib/python3.10/site-packages/plotly/express/_core.py", line 1341, in build_dataframe
    args["data_frame"] = pd.DataFrame(args["data_frame"])
  File "/home/wang-jian-an/venv-python310/lib/python3.10/site-packages/pandas/core/frame.py", line 733, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/wang-jian-an/venv-python310/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/home/wang-jian-an/venv-python310/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 114, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/home/wang-jian-an/venv-python310/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 667, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
[W 2024-01-25 11:16:01,470] Trial 0 failed with value None.
/tmp/ipykernel_2980907/3011311282.py:29: ExperimentalWarning:
WeightsAndBiasesCallback is experimental (supported from v2.9.0). The interface can change in the future.
/tmp/ipykernel_2980907/3011311282.py:36: ExperimentalWarning:
track_in_wandb is experimental (supported from v3.0.0). The interface can change in the future.
[I 2024-01-25 11:16:51,865] A new study created in memory with name: no-name-0e0a438a-4bab-4672-9a95-bfa4e9b4627f
[I 2024-01-25 11:16:52,213] Trial 0 finished with value: 0.9473684210526315 and parameters: {'min_samples_leaf': 4, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 0 with value: 0.9473684210526315.